FROM xwzliang/video-summarizer:0.0.2

RUN python -m pip install -i https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple "onnxruntime-gpu>=1.17" onnx ffmpeg-python Pillow fastapi uvicorn python-multipart
