services:
  transnetv2:
    image: xwzliang/transnetv2:0.0.2
    # user: "broliang"
    container_name: transnetv2
    networks:
      - mynet
    restart: always
    build: .
    # For Nvidia GPU's - You probably want to uncomment this
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    devices:
      - "/dev/dri:/dev/dri"
    # environment:
    #   - LD_LIBRARY_PATH=/opt/conda/lib/python3.11/site-packages/nvidia/cudnn/lib:${LD_LIBRARY_PATH}
    volumes:
      - ./inference:/tmp/inference:delegated
      - ~/videos:/data
      - /mnt/omv:/Volumes/omv
      - ~/models/.cache/huggingface:/root/.cache/huggingface:rshared
    ports:
      - "8007:8000"
    command: uvicorn server:app --app-dir /tmp/inference --host 0.0.0.0 --port 8000 --reload --log-level debug
networks:
  mynet:
    external: true